### ISSUE TITLE
Remove the Loading Message

### ISSUE THREAD

**Issue by dsawardekar** [dsawardekar/wordpress.vim#14]
WordPress.vim has a `Loading ...` message on startup. This was added to ensure that plugin loading is shown on slower systems.

I think we can remove this if the plugin loads fast enough.

Please +1 this issue if you agree. If not, post the perceived time between the `Loading ...` and the `Loading DONE` message.

**Comment by tnorthcutt** [comment]
I don' have a good sense of the perceived time between messages due to #15, but my suggestion would be to show the `DONE` message for, say, 5 seconds, and then remove it. I don't know how easy/hard that is (I'm not familiar with vimscript!), but I think it could be helpful to indicate that it has finished loading, while still not persisting the message for the entire Vim session.

**Comment by dsawardekar** [comment]
@tnorthcutt Deleting code is never hard. :smile: 

I'm more or less convinced to get rid of the message. Unless anyone else has some reasons not to, this should make it in the next version.

**Comment by dsawardekar** [comment]
@tnorthcutt Got rid of that pesky loading message. I can't say I'll miss it. :)
