### ISSUE TITLE
tags file is very large, over 1GB

### ISSUE THREAD

**Issue by salcode** [dsawardekar/wordpress.vim#16]
When the tags file is generating, the program appears to hang with the message "WordPress: Generating ctags ...".  After closing the program my tags file is over 3GB.

I had a similar problem when running ctags from the command line, which I corrected by excluding .git with the line `ctags --tag-relative -Rf.git/tags --exclude=node_modules --exclude=.git --languages=-javascript,sql`

I'm guessing the .git directory is not being excluded when generating ctags.

For reference, I'm using
MacVim - Snapshot 72, Vim 7.4
Exuberant Ctags 5.8
Configuration https://github.com/curtismchale/WPTT-Vim-Config

**Comment by dsawardekar** [comment]
Thanks for reporting this.

I hadn't noticed this as I was already doing this with my local `.ctags` configuration.

I'll exclude,
- .git
- node_modules
- bower_components
- build
- dist
- vendor

Any other directories that should be excluded?

**Comment by dsawardekar** [comment]
@salcode This is fixed in `0.1.16`. Please reopen if it's still not working.

**Comment by dsawardekar** [comment]
@salcode I haven't heard back from you, so I'm assuming this fix is working. Related to this, I found a variation of this bug on one of my boxes. The problem was to do with how excludes were passed in. That particular version of `ctags` was ignoring the exclude pattern.

Combined with the project containing a number `node_modules` folders which weren't excluded, ended up creating a very large `tags` file. 

I have made a better fix for this in `0.2.1`. Let me know if it breaks anything.
