### ISSUE TITLE
Continued CTags generation

### ISSUE THREAD

**Issue by curtismchale** [dsawardekar/wordpress.vim#17]
If you're trying to change tabs, use NERDTree, open in a new tab or a bunch of other commands CTags are generated each time.

This interrupts your workflow and it sucks.

![screen shot 2014-06-24 at 10 10 35 am](https://cloud.githubusercontent.com/assets/74561/3374791/84b55752-fbc2-11e3-8030-4202730c1824.png)

I'm using this Vim setup wit MacVim.

https://github.com/curtismchale/WPTT-Vim-Config

**Comment by curtismchale** [comment]
Should have also said that commenting this out of my Vundle setup makes the issue go away.

**Comment by dsawardekar** [comment]
@curtismchale I'm not sure I follow. WordPress.vim generates Ctags only once. The first time you open the project. This is done by creating a `tags` file in the same directory as the WordPress project root. 

Are you referring to some extra `ex-commands` that are generated? Please clarify.

**Comment by curtismchale** [comment]
Nope it goes through it's generation every time I do almost any command.

I'll do a screencast later today showing it.

**Comment by dsawardekar** [comment]
If it's regenerating Ctags again, that's definitely a bug. Something like a `screenr` would help me debug this.

**Comment by curtismchale** [comment]
Video https://www.dropbox.com/s/o0ofamnvorpm6lq/wordpress-vim-issue.mp4

**Comment by dsawardekar** [comment]
@curtismchale I may have stumbled upon the underlying cause of your issues with WordPress.vim. :smile: 

The `ctags` executable that comes with Mac OS X by default is not `Exuberant Ctags` at all. It's not even an older version, but a completely different program altogether.

WordPress.vim was picking the default `ctags` and running _it_ instead. Since that program won't generate a `tags` file you were seeing the `Generating Ctags` message every time.

I've improved the Ctags detection in `0.1.19` to check if the `ctags` executable is actually `exuberant ctags`. If not it will treat it as an invalid ctags executable.

If you haven't installed `exuberant ctags` it's done with `$ brew install ctags-exuberant`. Depending on your setup the system `ctags` might still take precedence. For that you need to setup your `PATH` with,

`export PATH="/usr/local/bin:$PATH"`

Else you can use WordPress.vim's configuration variable, `g:wordpress_vim_ctags_path` to point it to your custom ctags location.

That should also fix your other issues. Please reopen if it is still not working.

**Comment by curtismchale** [comment]
Well it seems to have 'fixed' it but now I have no :W commands available at all.

Guess I have to dig deeper.

**Comment by curtismchale** [comment]
I looked through the docs and couldn't find this: How do I tell wordpress.vim to regenerate the ctags?

**Comment by dsawardekar** [comment]
The tags regeneration command is `:Wctags!`. I think I may have forgotten to add it to the docs.

That will regenerate tags in your project's root directory. Note, if it says `ctags is missing` then it's not finding the right ctags program. If that's the case please post the output of running `:!ctags --version` or `:!ctags --help`.

**Comment by curtismchale** [comment]
This is what I get with `:!ctags --help`

``` bash
:!ctags --help
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...

shell returned 1 
```

`:!which ctags` gives me `/usr/bin/ctags`

**Comment by dsawardekar** [comment]
@curtismchale That isn't `Exuberant Ctags`, it's a different program part of Xcode.

Do you have [brew](http://brew.sh/) installed? That's the easiest way to get exuberant ctags. With brew you can install it with, `brew install ctags`. Then check if it was installed correctly with,

``` bash
$ which -a ctags
```

It should now show up in a path like `/usr/local/bin/ctags`.

**Comment by curtismchale** [comment]
Yup I have brew installed and it's got ctags-5.8 going.

Seems that my shell (zsh actually) has the proper ctags showing but MacVim shows `/usr/bin/ctags` followed by `/usr/local/bin/ctags`

**Comment by curtismchale** [comment]
Using the custom wordpress.vim var did fix ctags for me.

How long should ctags generation take in theory?

**Comment by dsawardekar** [comment]
> Using the custom wordpress.vim var did fix ctags for me.

Glad to hear that!

> How long should ctags generation take in theory?

It'll vary on different  systems. On stock WordPress about ~2 seconds. I have  a couple of larger projects with many plugins where it's about ~10 seconds.
